### ISSUE TITLE
线上node进程经常挂掉

### ISSUE THREAD

**Issue by Ben-Ben-B** [yi-ge/Koa2-API-Scaffold#10]
大神，我是个小白，我想问一下，怎么保证node.js服务器的进程一直进行啊，就你这个框架而言

**Comment by yi-ge** [comment]
这个只是一个脚手架，用的是koa2，它已经非常稳定可靠。可以使用pm2进行进程守护。此外，如果进程挂掉，一定有原因，需要找出来，确保线上业务不出问题。

**Comment by beclass** [comment]
pm2 start pm2.js  启动，访问不行呢

**Comment by yi-ge** [comment]
@laiyiyi 请使用pm2 logs查看错误日志。

**Comment by beclass** [comment]
@yi-ge大佬 日志没东西的，
![image](https://user-images.githubusercontent.com/12541388/48324397-7eeab400-e66b-11e8-96ee-0df00d558d12.png)

**Comment by yi-ge** [comment]
@laiyiyi `curl http://127.0.0.1:你的端口`，看下能不能正常返回。然后看防火墙以及到服务器控制面板，看一下控制面板的端口开放了没有。

**Comment by beclass** [comment]
@yi-ge 不行啊  返回curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused
npm run dev 这样启动，就正常。

**Comment by beclass** [comment]
@yi-ge 大佬，那个pm2 start  pm2.js 在你那能正常启动吗？  这种方式没效果，我只能直接pm2 start ./dist/app.js  -i 1   这样直接在命令上配置才行

**Comment by Ben-Ben-B** [comment]
@laiyiyi 你可以forever试试，我的就是用这个

**Comment by beclass** [comment]
@Ben199011 还是没效果，其他项目都没问题

**Comment by yi-ge** [comment]
@laiyiyi 你的报错说明本地端口都没监听，那肯定是启动报错了。贴一下pwd结果及pm2.json内容。

**Comment by beclass** [comment]
@yi-ge 大佬，这个是执行过程
http://182.92.215.85:8001/11.gif

**Comment by yi-ge** [comment]
@laiyiyi pm2.json没写对呀。添加cwd。或者用绝对路径。
![image](https://user-images.githubusercontent.com/6657330/48395251-9ef4a300-e751-11e8-9088-4380b200b657.png)

参考：

```javascript
{
  "apps": [{
    "name": "api",
    "script": "dist/main.js",
    "cwd": "/home/ubuntu/site/",
    "exec_mode": "fork",
    "max_memory_restart": "4G",
    "autorestart": true,
    "node_args": [],
    "args": [],
    "env": {

    }
  }]
}
```

**Comment by beclass** [comment]
@yi-ge 原来是这个名字的问题..
http://182.92.215.85:8001/22.gif

**Comment by yi-ge** [comment]
@laiyiyi 还有这种操作🤦‍♀️，谢谢！！谢谢！！

**Comment by zhuziyi1989** [comment]
你这启动脚本确实有问题。

**Comment by yi-ge** [comment]
@zhuziyi1989 很抱歉给您带来不便了。启动脚本的只是一个示例，实际使用一定要根据程序本身来修改的。比如说程序不支持微服务化，不支持多服务同时进行，就不能简单的fork启动。
