### ISSUE TITLE
请教下，这个怎么用vs断点调试呢？

### ISSUE THREAD

**Issue by beclass** [yi-ge/Koa2-API-Scaffold#12]
vs 里配置调试
  "program": "${workspaceFolder}/dist/app" 只能对构建后的才行。如何调试构建之前的呢？
  "program": "${workspaceFolder}/ ？"  这样启动npm run dev

**Comment by yi-ge** [comment]
方法跟普通的node.js程序一样。

**Comment by x363090973** [comment]
怎么用vscode调试项目？

**Comment by yi-ge** [comment]
@x363090973 请参考[https://cnodejs.org/topic/58f376fec749f63d48fe9548](https://cnodejs.org/topic/58f376fec749f63d48fe9548)
