### ISSUE TITLE
debug报错啊

### ISSUE THREAD

**Issue by boluo1230** [yi-ge/Koa2-API-Scaffold#14]
Break on start in file:///Users/liubolun/WebstormProjects/Koa2-API-Scaffold/build/dev-server.js:1
> 1 (function (exports, require, module, __filename, __dirname) { require('babel-register')
  2 require('../src/app')

这怎么解决啊亲

**Comment by yi-ge** [comment]
请问具体的报错内容是什么呢？

**Comment by yi-ge** [comment]
请检查一下`.babelrc`文件是否存在
