### ISSUE TITLE
线上部署问题

### ISSUE THREAD

**Issue by Nebulazheng** [yi-ge/Koa2-API-Scaffold#18]
楼主有没有部署都教程啊，我初学好难部署啊！
我在服务器上安装了node pm2 项目该如何启动起来。
我尝试用npm run dev 和npm run start去运行都提示es6都import语法错误
还有pm2启动项目是直接运行pm2.js吗还是钥自己写个配置文件
求恢复  急急急

**Comment by yi-ge** [comment]
与https://github.com/yi-ge/Koa2-API-Scaffold/issues/17 重复
