### ISSUE TITLE
会出一个TypeScript版本吗？

### ISSUE THREAD

**Issue by zouyaoji** [yi-ge/Koa2-API-Scaffold#19]
大佬会出一个TypeScript版本吗？

**Comment by yi-ge** [comment]
暂时不会。我改用fastify了，对TypeScript支持比较友好。

**Comment by zouyaoji** [comment]
哇~ 大佬啥时候开源个基于fastify的脚手架学习学习哇，hhh

**Comment by yi-ge** [comment]
@zouyaoji 近几年基于fastify做了一个开发框架，适时开放~

**Comment by zouyaoji** [comment]
期待期待~
