### ISSUE TITLE
node.js用什么数据库开发比较好？

### ISSUE THREAD

**Issue by Niofh** [yi-ge/Koa2-API-Scaffold#2]
因为本人接触mongodb一些基础，mysql不太懂。打算做一个项目用到支付模块，但是mongodb没有滚回，我该不该继续选用mongodb做数据库了？

**Comment by yi-ge** [comment]
如果没有mongodb开发经验，就不要用。你在做支付相关的业务，就用自己熟悉的，稳定就好。所以建议用MySQL数据库。
