### ISSUE TITLE
能问下登录认证在哪儿弄吗？

### ISSUE THREAD

**Issue by bitqiang** [yi-ge/Koa2-API-Scaffold#3]
![image](https://user-images.githubusercontent.com/13163400/31863143-d3a78fc4-b77b-11e7-9c4d-42497dbd129e.png)
一直执行这儿的代码。怎么，看不到懂为啥一直catch了。。

**Comment by yi-ge** [comment]
@bitqiang 登录认证需要用到Token。参考jsonwebtoken的说明。
