### ISSUE TITLE
线上部署问题

### ISSUE THREAD

**Issue by Ben-Ben-B** [yi-ge/Koa2-API-Scaffold#9]
远程服务器运行会报这个错误，本地运行时没有问题的，请问一下这个是什么问题啊
src/app.js -> dist/app.js
src/config.js -> dist/config.js
src/controllers/api.js -> dist/controllers/api.js
src/controllers/auth.js -> dist/controllers/auth.js
src/controllers/fosan.js -> dist/controllers/fosan.js
src/controllers/index.js -> dist/controllers/index.js
src/controllers/upload.js -> dist/controllers/upload.js
src/lib/PluginLoader.js -> dist/lib/PluginLoader.js
src/lib/sequelize.js -> dist/lib/sequelize.js
src/middleware/ErrorRoutesCatch.js -> dist/middleware/ErrorRoutesCatch.js
src/models/index.js -> dist/models/index.js
src/plugins/smtp_sendemail/index.js -> dist/plugins/smtp_sendemail/index.js
src/routes/error-routes.js -> dist/routes/error-routes.js
src/routes/main-routes.js -> dist/routes/main-routes.js
src/tool/Common.js -> dist/tool/Common.js
[root@iZ5iaszuifir7xZ fosan]# npm run production

> koa2-API-scaffold@1.0.0 production /root/fosan
> node dist/app.js

/root/fosan/node_modules/koa-jwt/lib/index.js:18
    const middleware = async function jwt(ctx, next) {
                             ^^^^^^^^

SyntaxError: Unexpected token function

**Comment by yi-ge** [comment]
你的node.js版本号是多少？尝试升级一下node.js的版本。

**Comment by Ben-Ben-B** [comment]
可以了，谢谢
